### ISSUE TITLE
Outdated information in Introduction to lartpc_mlreco3d Analysis Tools page

### ISSUE THREAD

**Issue by andrewmogan** [DeepLearnPhysics/lartpc_mlreco3d_tutorials#11]
- At the start of Section 2, `segment_label`, `fragment_label`, etc. should be updated to `segment`, `fragment`, etc.
- Several instances of `primaries` should be updated to `only_primaries` or `drop_nonprimary_particles`
- `mode='pt'` should be updated to `mode=pred_to_true`
- Section 4 bullets below particle matching block don't match the output shown in cell above

**Comment by Temigo** [comment]
This should be fixed now, thank you for reporting it!
